blog/config/routes.rb
Rails.application.routes.draw do
    devise_for :admins
    devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'welcome/index'
 
  resources :articles
 
  root 'welcome#index' #root path.
  	resources :articles do
  	resources :admins
  	resources :users
  	# resources :comments
	end
  # resources :articles, only: :index
end

blog/app/models/article.rb
#this class is inherited from ApplicationRecord.
require 'csv'
class Article < ApplicationRecord
	# has_many :comments
	mount_uploader :attchment, AttachmentUploader
	validates :title, presence: true,
					length: { minimum: 5 }

	def self.to_csv #Download File 
		CSV.generate do |csv|
			csv << column_names
			all.each do |article|
				csv << article.attributes.values_at(*column_names)
			end
		end
	end
end

blog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

blog/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

blog/app/controllers/accessible.rb
module Accessible
  extend ActiveSupport::Concern
  included do
    before_action :check_user
  end

  protected
  def check_user
    if current_admin
      flash.clear
      # if you have rails_admin. You can redirect anywhere really
      redirect_to(rails_admin.dashboard_path) && return
    elsif current_user
      flash.clear
      # The authenticated root path can be defined in your routes.rb in: devise_scope :user do...
      redirect_to(authenticated_user_root_path) && return
    end
  end
end

blog/app/controllers/admins/registrations_controller.rb
# frozen_string_literal: true
class Admins::RegistrationsController < Devise::RegistrationsController
  include Accessible
  skip_before_action :check_user, except: [:new, :create]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

blog/app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  include Accessible
  skip_before_action :check_user, only: :destroy
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

blog/app/controllers/articles_controller.rb
# This class is inherited from ApplicationController when you created new controller.
class ArticlesController < ApplicationController

  before_action :set_articles, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:index, :show, :new, :create]

def new
  @article = Article.new # initializing new article
end # new function end
 
def create
	@article = Article.new(article_params) 	 # creating new article and passing article_params
	if @article.save		 				 # check the new post is save d or not, if saved then redirect to the @article.
		redirect_to @article
		# redirect_to blogfiles_path, notice: "Successfully uploaded."
	else	
		render 'new' # otherwise render to new page.
	end
end					# create function end.

def index	 		# definig the index function to display the all posts.
	@articles = Article.all
	respond_to do |format|
		format.html
		format.csv { send_data @articles.to_csv }
	end
end		#  index function end.

public
def article_params 	# defination of article_params.
	params.require(:article).permit(:title, :text, :attachment)
end

def show	# show function to display the perticular post as per id.
	@article = Article.find(params[:id])								
end 	# show function end

def edit	# edit function to edit the existing blog.
	@article = Article.find(params[:id])
end		# edit fuinction end

def update	# update the blog.
	@article = Article.find(params[:id])
 
	if @article.update(article_params)
		redirect_to @article
	else
		render 'edit'
	end
end		# update function end

def destroy # delete the blog as per blog id.
	@article = Article.find(params[:id])
	@article.destroy
	redirect_to @article
end		# destroy function end 
end		# class end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

blog/app/controllers/users/sessions_controller.rb
# frozen_string_literal: true
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/blogfile_helper.rb
module BlogfileHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/views/articles/edit.html.erb
<html>
<head>
  <title>Edit Blog</title>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
       <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
    <style type="text/css" media="screen">
    body{
       background: linear-gradient(rgba(0,0,0,.7), rgba(0,0,0,.7)), url("https://unsplash.imgix.net/photo-1416339442236-8ceb164046f8?q=75&fm=jpg&s=8eb83df8a744544977722717b1ea4d09");
          background-repeat: no-repeat;
          background-size: cover;
          background-position: center center;
          color: #3191bfd6;
          height: 450px;
          padding-top: 50px;
    }
      #blog{
        margin: auto;
        width: 50%;
        padding: 10px;
      }
      #ex2{
        width: 50%;
      } 
      #ex4{
        width: 50%;
        height: 50%
      } 
     
      body{
        background-color: #2c5b7c;
      }
    </style>
</head>
<body>
    <div class = "clearfix">
  <div class = "container">
     <!-- <nav class="navbar navbar-full bg-success"> -->
    <p class="navbar-text pull-left">
      <%= link_to 'My Blog', controller: 'articles', class: 'navbar-brand'  %></p>
    <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= button_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Login", welcome_index_path, :class => 'navbar-link'  %>  
          <% end %>
        </p>
      </nav>
  </div>
</div>
  <div class = "container" id = "blog">
<h1>Edit article</h1>
<%= form_with(model: @article, local: true) do |form| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, class: 'form-control', id: 'ex2' %>
  </p>
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text,  class: 'form-control', id: 'ex4' %>
  </p>
    <p>
    <%= form.submit %>
  </p>
<%= link_to 'Back', articles_path, class: 'btn btn-primary' %>
<% end %> 
</div>
</body>
</html>

blog/app/views/articles/index.html.erb
<!-- Admin controls -->
<html>
<head>
	<title>Admin control Panel</title>
  <!-- Css style -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
       <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
  <style>
      table, td, th {
      border: 1px solid black; 
      margin-top: 50px;
    }
    table {
      border-collapse: collapse;
      width: 15%;
      background-color: white;
  }
  h1{
    text-align: center;
    color: #fdfbfb;
  }
   #header{
        background: white;
      }
      body{
       background: linear-gradient(rgba(0,0,0,.7), rgba(0,0,0,.7)), url("https://unsplash.imgix.net/photo-1416339442236-8ceb164046f8?q=75&fm=jpg&s=8eb83df8a744544977722717b1ea4d09");
          background-repeat: no-repeat;
          background-size: cover;
          background-position: center center;
          color: #3191bfd6;
          height: 450px;
          padding-top: 50px;
      }
  </style>
</head>
<body>
   <div class = "clearfix">
        <div class="container">
    <h1>Blogger Details</h1>
<p class="navbar-text pull-left">
      <span><%= link_to 'My Blog', controller: 'articles', class: 'navbar-brand'  %></span></p>
    <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= button_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Login",welcome_index_path, :class => 'navbar-link', align: 'left'  %>
          <% end %>
        </p>
      </div>
</div>
</div>
<div class = "container">
<table align="center" class="table table-bordered table-striped"> <!--Table tag used for displaying data in table format-->
  <tr class="info">
    <th>Title</th>
    <th>Text</th>
    <th colspan="3">Admin Controls</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <div class="btn-group">
      <td><%= link_to 'Show', article_path(article), class: 'btn btn-success'  %></td> <!-- redirect to show page as per perticular blog id-->
      <td><%= link_to 'Edit', edit_article_path(article), class: 'btn btn-primary' %></td> <!--redirect to Edit page-->
      <td><%= button_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
    </tr>
  <% end %>
</table>
  <center><%= link_to 'New article', new_article_path, class: 'btn btn-primary' %> <!--redirect to New article page-->
  <%= link_to "Download Blogs", articles_path(format: "csv"), class: 'btn btn-primary' %> <!--Download All blog in .csv format-->
  </center>
  </div> <!--create new Article-->
</div>
</body>
</html>

blog/app/views/articles/new.html.erb
<!DOCTYPE html> 
<html>
<head>
  <title>Blog</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
  <style type="text/css" media="screen">
      body{
          background: linear-gradient(rgba(0,0,0,.7), rgba(0,0,0,.7)), url("https://unsplash.imgix.net/photo-1416339442236-8ceb164046f8?q=75&fm=jpg&s=8eb83df8a744544977722717b1ea4d09");
          background-repeat: no-repeat;
          background-size: cover;
          background-position: center center;
          color: #3191bfd6;
          height: 450px;
          padding-top: 50px;
      }
      }
      #ex5{
        width: 50%;
      } 
      #ex6{
        width: 50%;
        height: 50%
      } 
      #blog{
        margin: auto;
        width: 50%;
        padding: 10px;
      }
      .md-form label {
            color: #ffffff;
        }
    </style>
</head>
<body>
  <div class = "bg">
  <div class = "clearfix">
    <div class="container">
      <h2>Blog</h2>
        <p class="navbar-text pull-left">
          <%= link_to 'My Blog', controller: 'articles', class: 'navbar-brand'  %></p>
            <p class="navbar-text pull-right">
              <% if user_signed_in? %>
              Logged in as <strong><%= current_user.email %></strong>.
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
              <%= button_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
              <% else %>
              <p class="navbar-text pull-left">
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></p>
            <% end %>
        </p>
      </div>
</div>
</div>
  <div class = "container" id = "blog">
  <%= form_with model: @article, local: true do |form| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <strong><%= form.label :title %></strong><br>
    <%= form.text_field :title, id: 'ex5' %>
  </p>
  <br>
  <p>
    <strong><%= form.label :text  %></strong><br>
    <%= form.text_area :text, class: 'form-control', id: 'ex6' %>
  </p>
  <p>
    <%= form.submit %>  
     <%= form.file_field :attachment %> <!-- Upload file -->
  </p>
<% end %>
<%= link_to 'Back', articles_path, class: 'btn btn-primary' %>
</div>
</div>
</body>
</html>

blog/app/views/articles/show.html.erb
  <!DOCTYPE html>
  <html>
  <head>
    <title>New Article</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
  <style type="text/css">
  body{
     background: linear-gradient(rgba(0,0,0,.7), rgba(0,0,0,.7)), url("https://unsplash.imgix.net/photo-1416339442236-8ceb164046f8?q=75&fm=jpg&s=8eb83df8a744544977722717b1ea4d09");
          background-repeat: no-repeat;
          background-size: cover;
          background-position: center center;
          color: #3191bfd6;
          height: 450px;
          padding-top: 50px;
  }
    p,b{
      margin-top: 10px;
      padding: 50px;
    }
  </style>
   </head>
  <body>
    <div class = "container">
    <div class="well well-lg">
      <p>
        <b>Title</b>
        <%= @article.title %> <!-- Displaying Blog tile-->
      </p>
      <p>
       <b>Text</b>
        <%= @article.text %> <!-- Displaying Blog text-->
      </p>
      <%= link_to 'New article', article_path, class: 'btn btn-primary' %> <!-- Create new blog-->
      <%= link_to 'My Blog', controller: 'articles' %>
      </div> <!-- Displaying all blog-->
      </div>
    </div>
  <body>
  <html>
  

blog/app/views/welcome/index.html.erb
<!-- Index page -->
<html>
<head>
	<title>Bloggersite</title>
	<meta charset="utf-8">
	  <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <!-- Latest compiled and minified CSS -->
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

	  	<!-- jQuery library -->
	  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

	  	<!-- Latest compiled JavaScript -->
	  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 
	  <style type="text/css" media="screen">
	  	body{
	  		background: linear-gradient(rgba(0,0,0,.7), rgba(0,0,0,.7)), url("https://unsplash.imgix.net/photo-1416339442236-8ceb164046f8?q=75&fm=jpg&s=8eb83df8a744544977722717b1ea4d09");
		      background-repeat: no-repeat;
		      background-size: cover;
		      background-position: center center;
		      color: #fff;
		      height: 450px;
		      padding-top: 50px;
	  	}	
	p{
		    font-size: 24px
	}
    </style>
</head>
<body>
   <div class = "clearfix">
	<div class = "container">
	        <h1>Welcome to Ruby on Rails Blog!</h1>
 	 <!-- <nav class="navbar navbar-full navbar-dark bg-success"> -->
		<p class="navbar-text pull-left">
			<%= link_to 'My Blog', controller: 'articles', class: 'navbar-brand'  %>  
		<p class="navbar-text pull-right">
         <%= link_to 'Admin Login', new_admin_session_path, :class => 'navbar-link' %> 
           <%= link_to 'User Login', new_user_session_path, :class => 'navbar-link' %>
            </p>
    </div>
</div>
</div>
</body>
</html>