testblog/config/routes.rb
Rails.application.routes.draw do
  # get '/users/sign_out' => 'devise/sessions#destroy'
devise_for :users, path: 'users'
# eg. http://localhost:3000/users/sign_in
devise_for :admins, path: 'admins'
# eg. http://localhost:3000/admins/sign_in

  get 'welcome/index'

  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
   #devise_for :admins
   
 	resources :posts do
 	resources :admins
 	resources :users
	 end

	 resources :posts ,only: :index
 #devise_for :users 

 #resources :posts do
 	
 #end

end

testblog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

testblog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

testblog/app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Welcome</title>
		<!-- Latest compiled and minified CSS -->
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  		<!-- jQuery library -->
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 		<!-- Popper JS -->
  	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  		<!-- Latest compiled JavaScript -->
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <style>
      .but1{
          margin-left: 110px;
          margin-top: -67px;
      }
      .but2{
        margin-right: 52px;
      }
    </style>
</head>
<body>
	<div class="container shadow-lg p-3 mb-5 bg-white rounded border">
    <!-- navbar start-->
		<nav class="navbar navbar-full bg-sucess">
  		<p class="navbar-text pull-left">
  		  <%=link_to'Home'%>
  		  <%=link_to'About'%>
  		  <%=link_to'Contect us'%>
  		</p>
      <div style="float: right">
  		<!--<p class="navbar-text pull-right"> -->
		    <% if user_signed_in? %>
  				<!--Logged in as <strong><%= current_user.email %></strong>.-->
  				<%= link_to "<button type='button' class='btn btn-success but2'>Edit profile</button>".html_safe,  edit_user_registration_path, :class => 'navbar-link' %>|<%= button_to"logout",destroy_user_session_path, method: :delete, class: 'btn btn-danger but1' %>
        <% elsif admin_signed_in? %>
          <%= button_to"logout",destroy_admin_session_path, method: :delete, class: 'btn btn-danger but1' %>
			  <% else %>
         <%= link_to 'Admin Login', new_admin_session_path, :class => 'navbar-link' %> | 
           <%= link_to 'User Login', new_user_session_path, :class => 'navbar-link' %>    
			  <% end %>
		  <!--</p> -->
      </div>
		</nav>
    <!-- navbar end -->
    <div class="container" align="center">
      <h1>Hello Rails..!</h1>
        <% if user_signed_in? || admin_signed_in? %>
          <%=link_to'My Blog',controller: 'posts' %>
        <% end %>
    </div>
      
         
				
</body>
</html>